//package br.gov.caixa.simtx.simulador.services.sitax;
//
//
//import java.util.logging.Logger;
//
//import javax.jws.WebService;
//
///**
// * This class was generated by Apache CXF 3.1.17
// * 2018-11-08T15:35:22.453-02:00
// * Generated source version: 3.1.17
// * 
// */
//
//@WebService(
//          serviceName = "PagamentoBoletoLoteImplService",
//          portName = "PagamentoBoletoLoteSOAPPort",
//          targetNamespace = "http://caixa.gov.br/simtx/pagamento_boleto_lote/v1/ns",
//          wsdlLocation = "file:/C:/Caixa/SIMTX/GIT/simtx-api/simtx-roteador-api/src/main/webapp/WEB-INF/wsdl/Pagamento_Boleto_Lote.wsdl",
//          endpointInterface = "br.gov.caixa.simtx.pagamento_boleto_lote.v1.ns.PagamentoBoletoLoteImplService")
//public class ConsultaContaSITAX implements ConsultaContaSITAXService {
//
//    private static final Logger LOG = Logger.getLogger(ConsultaContaSITAX.class.getName());
//
//    public ConsultaRegrasBoletoSaida cadastrar(ConsultaRegrasBoletoEntrada parameters) { 
//        LOG.info("Executing operation cadastrar");
//        System.out.println(parameters);
//        try {
//        	ConsultaRegrasBoletoSaida _return = new ConsultaRegrasBoletoSaida();
//            Header _returnHEADER = new Header();
//            _returnHEADER.setVersao("VERSAO1557267904");
//            _returnHEADER.setAutenticacao("AUTENTICACAO-314197785");
//            _returnHEADER.setUsuarioServico("USUARIOSERVICO1605779070");
//            _returnHEADER.setUsuario("USUARIO-378276514");
//            _returnHEADER.setOperacao("OPERACAO-2119200459");
//            _returnHEADER.setIndice(Integer.valueOf(-1844647373));
//            _returnHEADER.setSistemaOrigem("SISTEMAORIGEM-1869903502");
//            _returnHEADER.setUnidade("UNIDADE1356369430");
//            _returnHEADER.setIdentificadorOrigem("IDENTIFICADORORIGEM199824996");
//            _returnHEADER.setDataHora("DATAHORA-1513399489");
//            _returnHEADER.setIdProcesso("IDPROCESSO1038665871");
//            _return.setHeader(_returnHEADER);
//            _return.setCodRetorno("CODRETORNO1410637097");
//            _return.setOrigemRetorno("ORIGEMRETORNO621496620");
//            _return.setMsgRetorno("MSGRETORNO1640073100");
//            ConsultaRegrasBoletoDadosSaida _returnDADOS = new ConsultaRegrasBoletoDadosSaida();
//            _returnDADOS.setFormaRecebimento("VALOR_CALCULADO");
//            _returnDADOS.setValorNominal(new java.math.BigDecimal("8260554976488143181.2590191972459570537"));
//            _returnDADOS.setDataVencimento("DATAVENCIMENTO-1535535971");
//            _return.setDados(_returnDADOS);
//            return _return;
//        } catch (java.lang.Exception ex) {
//            ex.printStackTrace();
//            throw new RuntimeException(ex);
//        }
//    }
//
//}
//
