//package br.gov.caixa.simtx.simulador.services.sitax;
//
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.jws.soap.SOAPBinding;
//
///**
// * This class was generated by Apache CXF 3.1.17
// * 2018-11-08T15:35:22.619-02:00
// * Generated source version: 3.1.17
// * 
// */
//@WebService
//@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
//public interface ConsultaContaSITAXService {
//
//    @WebMethod(action = "http://caixa.gov.br/siatr/limite/efetiva/req")
//    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/siatr/limite/efetiva/resp", partName = "parameters")
//    public ConsultaRegrasBoletoSaida cadastrar(
//        @WebParam(partName = "parameters", name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/siatr/limite/efetiva/req")
//        ConsultaRegrasBoletoEntrada parameters
//    );
//}
//
